const $=x=>document.getElementById(x),C=['low','medium','high'];let stream,rec,trials=[],i=-1,now,ctx,buffers={},chunks=[],started,db;
const say=x=>$('status').textContent=x, safe=x=>x.replace(/[^\w-]/g,'_'), stamp=x=>x.toISOString().replaceAll(':','-');
$('files').innerHTML=C.map(c=>[1,2,3].map(n=>`<label>${({low:'低',medium:'中',high:'高'}[c])}複雑性 ${n}<input id="${c}${n}" type="file" accept="audio/*"></label>`).join('')).join('');
function open(){return new Promise((y,n)=>{let r=indexedDB.open('groove',1);r.onupgradeneeded=()=>r.result.createObjectStore('r',{keyPath:'id'});r.onsuccess=()=>y(r.result);r.onerror=()=>n(r.error)})}function put(x){return new Promise((y,n)=>{let r=db.transaction('r','readwrite').objectStore('r').put(x);r.onsuccess=y;r.onerror=()=>n(r.error)})}function all(){return new Promise((y,n)=>{let r=db.transaction('r').objectStore('r').getAll();r.onsuccess=()=>y(r.result);r.onerror=()=>n(r.error)})}
$('prepare').onclick=async()=>{let files={};for(let c of C)for(let n=1;n<4;n++)files[c+n]=$(c+n).files[0];if(!$('e').value||!$('p').value)return say('実験者IDと参加者IDを入力してください。');if(Object.values(files).some(x=>!x))return say('9音源すべてを選択してください。');try{ctx??=new AudioContext();buffers={};say('9音源の再生可能性を確認中…');for(let[k,f]of Object.entries(files))buffers[k]={b:await ctx.decodeAudioData(await f.arrayBuffer()),name:f.name}}catch(e){return say('音源を読み込めません。iPadで再生できるMP3/M4A/WAVを選んでください。')}let tasks=$('o').value==='a'?['腕振り','自由身体運動']:['自由身体運動','腕振り'];trials=[];tasks.forEach(t=>{let b=[];for(let c of C)for(let n=1;n<4;n++)b.push({task:t,c,key:c+n,name:buffers[c+n].name});b.sort(()=>Math.random()-.5);trials.push(...b)});i=-1;$('camera').disabled=false;$('trial').textContent=`18試行を作成。最初は${tasks[0]}です。`;say('9音源を正常にデコードしました。カメラを開始してください。')};
$('camera').onclick=async()=>{try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});$('v').srcObject=stream;$('start').disabled=false;say('カメラ映像を確認しました。最初の試行を開始してください。')}catch(e){say('カメラを開始できません: '+e.message)}};
$('start').onclick=async()=>{try{await ctx.resume();next()}catch(e){say('音源出力を開始できません: '+e.message)}};$('block').onclick=()=>{$('block').disabled=true;next()};
function next(){i++;if(i>=trials.length){$('trial').textContent='全18試行完了。下のデータをファイルへ保存してください。';return say('実験完了。')}if(i&&trials[i].task!==trials[i-1].task){i--;$('block').disabled=false;$('block').textContent=`「${trials[i+1].task}」を開始`;$('trial').textContent='課題ブロック終了。次を手動で開始します。';return}now=trials[i];record()}
function record(){chunks=[];started=new Date;let type=MediaRecorder.isTypeSupported('video/mp4')?'video/mp4':'';try{rec=type?new MediaRecorder(stream,{mimeType:type,videoBitsPerSecond:3000000}):new MediaRecorder(stream)}catch(e){return say('録画開始失敗: '+e.message)}rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onerror=e=>say('録画エラー: '+e.error.message);rec.onstop=save;rec.start(1000);if(rec.state!=='recording')return say('録画を開始できませんでした。');$('rec').textContent='● 録画中';$('trial').textContent=`${i+1}/18 ${now.task} ${now.c} ${now.name}：200フレーム待機`;frames()}
function frames(){if('requestVideoFrameCallback'in HTMLVideoElement.prototype){let n=0,t=()=>$('v').requestVideoFrameCallback(()=>++n>=200?play():t());t()}else setTimeout(play,6700)}function play(){let s=ctx.createBufferSource();s.buffer=buffers[now.key].b;s.connect(ctx.destination);s.onended=()=>rec.state==='recording'&&rec.stop();try{s.start();$('trial').textContent=`${i+1}/18 音源再生中：${now.name}`}catch(e){say('音源再生失敗: '+e.message);rec.stop()}}
async function save(){let end=new Date,type=rec.mimeType||'video/mp4',ext=type.includes('webm')?'webm':'mp4',name=`${safe($('p').value)}_${now.task}_${now.key}_${stamp(started)}`,meta={experimenter_id:$('e').value,participant_id:$('p').value,trial:i+1,task:now.task,condition:now.c,stimulus_id:now.key,stimulus_file:now.name,started_at:started.toISOString(),finished_at:end.toISOString(),audio_start_frame_offset:200,video_file:name+'.'+ext};try{await put({id:crypto.randomUUID(),name,at:+started,type,video:new Blob(chunks,{type}),meta});await render()}catch(e){return say('iPad内保存失敗: '+e.message)}$('rec').textContent='';let r=Math.max(0,+$('rest').value||0);$('trial').textContent=`${i+1}/18を保存。${r}秒後に次を開始`;setTimeout(next,r*1000)}
async function render(){let rows=await all();$('list').innerHTML=rows.length?'':'保存データはありません。';rows.sort((a,b)=>b.at-a.at).forEach(r=>{let d=document.createElement('div');d.className='item';d.innerHTML=`<b>${r.name}</b><br>${r.meta.task} / ${r.meta.stimulus_file}<br>`;let b=document.createElement('button');b.textContent='動画とJSONをファイルに保存';b.onclick=()=>exportR(r);d.append(b);$('list').append(d)})}async function exportR(r){let ext=r.type.includes('webm')?'webm':'mp4',f=[new File([r.video],r.name+'.'+ext,{type:r.type}),new File([JSON.stringify(r.meta,null,2)],r.name+'.json',{type:'application/json'})];try{if(navigator.canShare?.({files:f}))return await navigator.share({files:f})}catch(e){if(e.name==='AbortError')return}f.forEach(x=>{let a=document.createElement('a');a.href=URL.createObjectURL(x);a.download=x.name;a.click()})}
open().then(x=>{db=x;render()}).catch(e=>say('iPad内ストレージを開けません: '+e.message));
