const $=id=>document.getElementById(id),CONDS=['low','medium','high'];let db,stream,rec,ctx,buffers={},trials=[],i=-1,current,chunks,started;
const say=x=>$('status').textContent=x, safe=x=>x.replace(/[^\w-]/g,'_'), stamp=d=>d.toISOString().replaceAll(':','-');
$('soundInputs').innerHTML=CONDS.map(c=>[1,2,3].map(n=>`<label>${({low:'低',medium:'中',high:'高'}[c])}複雑性 ${n}<input id="${c}${n}" type="file"></label>`).join('')).join('');
function open(){return new Promise((y,n)=>{let r=indexedDB.open('groove-v2',1);r.onupgradeneeded=()=>r.result.createObjectStore('records',{keyPath:'id'});r.onsuccess=()=>y(r.result);r.onerror=()=>n(r.error)})}function put(x){return new Promise((y,n)=>{let r=db.transaction('records','readwrite').objectStore('records').put(x);r.onsuccess=y;r.onerror=()=>n(r.error)})}function all(){return new Promise((y,n)=>{let r=db.transaction('records').objectStore('records').getAll();r.onsuccess=()=>y(r.result);r.onerror=()=>n(r.error)})}
$('prepare').onclick=async()=>{let f={};for(let c of CONDS)for(let n=1;n<4;n++)f[c+n]=$(c+n).files[0];if(!$('experimenter').value||!$('participant').value)return say('実験者IDと参加者IDを入力してください。');if(Object.values(f).some(x=>!x))return say('9音源すべてを選択してください。');try{ctx??=new AudioContext();buffers={};say('9音源を読み込み、再生可能か確認しています…');for(const[k,x]of Object.entries(f))buffers[k]={b:await ctx.decodeAudioData(await x.arrayBuffer()),name:x.name}}catch(e){return say('音源を読み込めません。iPadで再生できるMP3/M4A/WAVを選んでください。')}let ts=$('order').value==='arm'?['腕振り','自由身体運動']:['自由身体運動','腕振り'];trials=[];ts.forEach(task=>{let b=[];for(let c of CONDS)for(let n=1;n<4;n++)b.push({task,c,key:c+n,name:buffers[c+n].name});b.sort(()=>Math.random()-.5);trials.push(...b)});i=-1;$('camera').disabled=false;$('trial').textContent=`18試行を作成。最初は${ts[0]}です。`;say('9音源をデコード済みです。カメラ・マイクを開始してください。')};
$('camera').onclick=async()=>{try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:true});$('v').srcObject=stream;$('start').disabled=false;say('カメラとマイクを開始しました。開始前に実機で音声入力を確認してください。')}catch(e){say('カメラ／マイクを開始できません: '+e.message)}};
$('start').onclick=async()=>{try{await ctx.resume();next()}catch(e){say('音源出力を開始できません: '+e.message)}};$('block').onclick=()=>{$('block').disabled=true;next()};
function next(){i++;if(i>=trials.length){$('trial').textContent='全18試行完了。一括ダウンロードでiCloud Driveへ保存してください。';return say('実験完了。')}if(i&&trials[i].task!==trials[i-1].task){i--;$('block').disabled=false;$('block').textContent=`「${trials[i+1].task}」ブロックを開始`;$('trial').textContent='課題ブロック終了。次を手動で開始します。';return}current=trials[i];startRecord()}
function startRecord(){chunks=[];started=new Date;let type=MediaRecorder.isTypeSupported('video/mp4')?'video/mp4':'';try{rec=type?new MediaRecorder(stream,{mimeType:type,videoBitsPerSecond:3000000}):new MediaRecorder(stream)}catch(e){return say('録画開始失敗: '+e.message)}rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onerror=e=>say('録画エラー: '+(e.error?.message||''));rec.onstop=save;rec.start(1000);if(rec.state!=='recording')return say('録画を開始できませんでした。');$('recording').textContent='● 録画中（マイク音声を含む）';$('trial').textContent=`${i+1}/18 ${current.task} ${current.name}：200フレーム待機`;waitFrames()}
function waitFrames(){if('requestVideoFrameCallback'in HTMLVideoElement.prototype){let n=0,t=()=>$('v').requestVideoFrameCallback(()=>++n>=200?play():t());t()}else setTimeout(play,6700)}function play(){let s=ctx.createBufferSource();s.buffer=buffers[current.key].b;s.connect(ctx.destination);s.onended=()=>rec?.state==='recording'&&rec.stop();try{s.start();$('trial').textContent=`${i+1}/18 音源再生中：${current.name}`}catch(e){say('音源再生失敗: '+e.message);rec.stop()}}
async function save(){let end=new Date,type=rec.mimeType||'video/mp4',ext=type.includes('webm')?'webm':'mp4',name=`${safe($('participant').value)}_${current.task}_${current.key}_${stamp(started)}`,meta={experimenter_id:$('experimenter').value,participant_id:$('participant').value,trial:i+1,task:current.task,condition:current.c,stimulus_id:current.key,stimulus_file:current.name,started_at:started.toISOString(),finished_at:end.toISOString(),audio_start_frame_offset:200,video_file:name+'.'+ext,recording_includes_microphone_audio:true};try{await put({id:crypto.randomUUID(),name,at:+started,type,video:new Blob(chunks,{type}),meta});render()}catch(e){return say('iPad内保存失敗: '+e.message)}$('recording').textContent='';let r=Math.max(0,+$('rest').value||0);$('trial').textContent=`${i+1}/18を保存。${r}秒後に次を開始`;setTimeout(next,r*1000)}
function esc(v){return '"'+String(v??'').replaceAll('"','""')+'"'}async function csv(rows){let keys=['experimenter_id','participant_id','trial','task','condition','stimulus_id','stimulus_file','started_at','finished_at','audio_start_frame_offset','video_file','recording_includes_microphone_audio'];return [keys.join(','),...rows.map(r=>keys.map(k=>esc(r.meta[k])).join(','))].join('\r\n')}
function u16(n){return [n&255,n>>8&255]}function u32(n){return [...u16(n),...u16(n>>>16)]}const crcTable=(()=>{let a=[];for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;a[n]=c>>>0}return a})();function crc(data){let c=0xffffffff;for(let x of data)c=crcTable[(c^x)&255]^(c>>>8);return(c^0xffffffff)>>>0}async function zip(files){let enc=new TextEncoder(),parts=[],dir=[],off=0;for(let f of files){let name=enc.encode(f.name),data=new Uint8Array(await f.blob.arrayBuffer()),sum=crc(data),head=new Uint8Array([80,75,3,4,20,0,0,0,0,0,0,0,0,0,...u32(sum),...u32(data.length),...u32(data.length),...u16(name.length),0,...name]);parts.push(head,data);let d=new Uint8Array([80,75,1,2,20,0,20,0,0,0,0,0,0,0,0,0,...u32(sum),...u32(data.length),...u32(data.length),...u16(name.length),0,0,0,0,0,0,0,0,0,0,0,0,...u32(off),...name]);dir.push(d);off+=head.length+data.length}let size=dir.reduce((n,x)=>n+x.length,0),end=new Uint8Array([80,75,5,6,0,0,0,0,...u16(dir.length),...u16(dir.length),...u32(size),...u32(off),0,0]);return new Blob([...parts,...dir,end],{type:'application/zip'})}
async function exportAll(){let rows=await all();if(!rows.length)return say('書き出す試行がありません。');let files=rows.map(r=>({name:r.meta.video_file,blob:r.video}));files.push({name:`${safe($('participant').value)}_metadata.csv`,blob:new Blob([await csv(rows)],{type:'text/csv;charset=utf-8'})});let file=new File([await zip(files)],`${safe($('participant').value)}_groove_experiment.zip`,{type:'application/zip'});try{if(navigator.canShare?.({files:[file]})){await navigator.share({title:'Groove Experiment',files:[file]});say('共有シートで「ファイルに保存」→「iCloud Drive」を選んでください。');return}}catch(e){if(e.name==='AbortError')return}let a=document.createElement('a');a.href=URL.createObjectURL(file);a.download=file.name;a.click()}
async function render(){let rows=await all(),box=$('records');box.innerHTML=rows.length?'':'保存データはありません。';rows.forEach(r=>{let d=document.createElement('div');d.className='item';d.innerHTML=`<b>${r.name}</b><br>${r.meta.task} / ${r.meta.stimulus_file}`;box.append(d)})}$('exportAll').onclick=exportAll;open().then(x=>{db=x;render()}).catch(e=>say('iPad内ストレージを開けません: '+e.message));
